let baseLayout = require("./layouts/base.js");

module.exports = function() {
    let pageContent = html`
        <section class="pa4 pt5">
            <h2>Content styles</h2>
            <p>For basic markup generated by users through a Rich Text Editor / tralslated from MarkDown / that kind of thing.</p>
        </section>
        <section class="pa4" id="headings">
            <h3>Headings</h3>    
            <h1>H1 Giant Banner</h1>
            <h2>H2 Page Title</h2>
            <h3>H3 Section title</h3>
            <h4>H4 Sub Section title</h4>
            <h5>H5 This is essentially paragraph text size</h5>
            <h6>H6 Teeny tiny things!</h6>
        </section>
        <section class="pa4" id="paragraphs">
            <h3>Paragraphs</h3>
            <p>Prow scuttle parrel provost Sail ho shrouds spirits boom mizzenmast yardarm. Pinnace holystone mizzenmast quarter crow's nest <em>nipperkin grog</em> yardarm hempen halter furl. Swab barque interloper chantey doubloon starboard grog black jack gangway rutters.</p>            
            <p>Deadlights jack lad schooner scallywag dance the hempen jig carouser broadside cable strike colors. Bring a spring upon her cable holystone blow the man down spanker Shiver me timbers <a href="#">here's a link!</a> to go on account lookout wherry doubloon chase. Belay yo-ho-ho keelhaul squiffy black spot yardarm spyglass sheet transom heave to.</p>
            <p>Trysail Sail ho Corsair red ensign hulk <strong>smartly boom jib</strong> rum gangway. Case shot Shiver me timbers gangplank crack Jennys tea cup ballast Blimey lee snow crow's nest rutters. Fluke jib scourge of the seven seas boatswain schooner gaff booty Jack Tar transom spirits.</p>
        </section>
        <section class="pa4" id="links">   
            <h3>Links and underlines</h3>
            <p><a href="#">[p > a] Links with default underline <br/>clipping descending letters depends on browser.</a></p>
            <a href="#">[a] Link with default underline <br/>(a tags are inline elements, so they don't pop in a margin-bottom, because it wouldn't do anything anyway.)</a>
            <br />&nbsp;
            <p><span class="underline">[p > span.underline] Pretty text underline without <br/>clipping</span> descending letters.</p>
            <p class="underline">[p.underline] Pretty text underline without <br/>clipping descending letters. (probably don't put the underline class directly on a p... unless you want only the first line to be underlined?)</p>
            <p><a class="underline">[p > a.underline] a link within a p </br />and the underline gqy|</a></p>
            <a class="underline">[a.underline] just an a with <br />the underline class</a>
            
        </section>
        <section class="pa4" id="lists">
            <h3>Lists</h3>
            <ul>
                <li>First</li>
                <li>Second</li>
                <li>Third</li>
                <li>
                    Fourth
                    <ul>
                        <li>First</li>
                        <li>Second</li>
                        <li>Third</li>
                    </ul>
                </li>
                <li>Fifth</li>
                <li>Sixth</li>
                <li>Seventh</li>
            </ul>
            <ol>
                <li>First</li>
                <li>Second</li>
                <li>Third</li>
            </ol>
        </section>
        <section class="pa4" id="tables">
            <h3>Tables</h3>
            <table>
                <caption>
                    Table caption: not strictly required but it helps with accessibility.
                </caption>
                <thead>
                    <tr>
                        <th>Table heading</th>
                        <th>Table heading</th>
                        <th>Table heading</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Table cell</td>
                        <td>Table cell</td>
                        <td>Table cell</td>
                    </tr>
                    <tr>
                        <td>Table cell</td>
                        <td>Table cell</td>
                        <td>Table cell</td>
                    </tr>
                    <tr>
                        <td>Table cell</td>
                        <td>Table cell</td>
                        <td>Table cell</td>
                    </tr>
                </tbody>
            </table>
        </section>
        <section class="pa4" id="others">
            <h3>Other elements</h3>
            <blockquote>
                The attention grabbing blockquote, ripe to fill with wisdom nuggets.
            </blockquote>
            <p>An <code>inline block of code</code>.</p>
            <pre><code>module.exports = function(){
    return html\`
        &lt;pre&gt;&lt;code&gt;A pre code!&lt/code&gt&lt/pre&gt
    \`
} </code></pre>
        </section>
    `;

    return baseLayout(pageContent);
};
